jQuery.cookie=function(b,a,c){if(typeof a!="undefined"){c=c||{};if(a===null){a="";c.expires=-1}var e="";if(c.expires&&(typeof c.expires=="number"||c.expires.toUTCString)){if(typeof c.expires=="number"){e=new Date;e.setTime(e.getTime()+c.expires*24*60*60*1E3)}else e=c.expires;e="; expires="+e.toUTCString()}var g=c.path?"; path="+c.path:"",k=c.domain?"; domain="+c.domain:"";c=c.secure?"; secure":"";document.cookie=[b,"=",encodeURIComponent(a),e,g,k,c].join("")}else{a=null;if(document.cookie&&document.cookie!=
""){c=document.cookie.split(";");for(e=0;e<c.length;e++){g=jQuery.trim(c[e]);if(g.substring(0,b.length+1)==b+"="){a=decodeURIComponent(g.substring(b.length+1));break}}}return a}};
var T_No=0,T_Name=1,T_StnFirstName=2,T_StnFirst=3,T_StnLastName=4,T_StnLast=5,T_StnFromName=6,T_StnFrom=7,T_StnToName=8,T_StnTo=9,T_Departure=10,T_Arrival=11,T_Travel=12,T_RunDays=13,T_Mon=14,T_Tues=15,T_Wed=16,T_Thur=17,T_Fri=18,T_Sat=19,T_Sun=20,T_Classes=21,T_1A=22,T_2A=23,T_3A=24,T_CC=25,T_FC=26,T_SL=27,T_2S=28,T_3E=29,T_2H=30,T_BlankClass=31,T_TrainType=32,T_TrainID=33,T_RunningDayToStn=34,T_Pantry=35,T_DataSource=36,T_DateFrom=37,T_DateTo=38,T_Distance=39,T_AvSpeed=40,T_Fare=41,T_IsDuronto=
42,T_IsGaribRath=43,T_Note=44,T_ARP=45,T_RunningDayFromStn=46,T_TrainNoAlias=47,T_AdminNote=48,T_After=49,T_TrainType2=50,T_WaitTotal=51,T_Status=52,T_OwningRailway=53,T_Division=54,T_Guage=55,T_RakeShare=56,T_Reverse=57,T_Flags=58,F_Show_General_Fare=0,F_Food_Cost_Included=1,F_Download_Full_Route_Fare=2;
function TrainList(b,a,c,e){this.IsMobile=e==undefined?0:e;this.ObjectName=c;this.SelectedTrain=null;this.CH=[[60,T[4][L],T[11][L],T_No],[165,T[5][L],T[12][L],T_Name],[12,"P",T[13][L],T_Pantry],[42,T[6][L],T[14][L],T_StnFrom],[42,T[8][L],T[15][L],T_Departure],[42,T[7][L],T[16][L],T_StnTo],[42,T[9][L],T[17][L],T_Arrival],[40,T[10][L],T[18][L],T_Travel],[12,"R",T[19][L],T_RunDays],[15,"M",T[20][L],T_Mon],[15,"T",T[21][L],T_Tues],[15,"W",T[22][L],T_Wed],[15,"T",T[23][L],T_Thur],[15,"F",T[24][L],T_Fri],
[15,"S",T[25][L],T_Sat],[15,"<span style='color: red'>S</span>",T[26][L],T_Sun],[5,"&nbsp;","",0],[20,"1A",T[27][L],T_1A],[20,"2A",T[28][L],T_2A],[20,"3A",T[29][L],T_3A],[20,"CC",T[30][L],T_CC],[20,"FC",T[31][L],T_FC],[20,"SL",T[32][L],T_SL],[20,"2S",T[33][L],T_2S],[20,"3E",T[34][L],T_3E],[40,T[132][L],T[132][L],T_After],[40,T[134][L],T[135][L],T_WaitTotal]];this.IsMainSearch=1;if(this.ObjectName=="TrainsVia"){this.CH[0][0]=40;this.CH[1][0]=139;this.CH[3][0]=this.CH[4][0]=this.CH[5][0]=this.CH[6][0]=
35;for(c=17;c<=24;c++)this.CH[c][0]=19;this.IsMainSearch=0}this.Trains=[];this.SortedCol=0;this.DataDiv="#"+a;this.lastSelectedRow=null;b=b.split("^");this.IsMainSearch==0&&this.CalcFirstTrainTime();this.DataTime=null;for(c=0;c<b.length;c++){b[c]+="~~~~~~";this.Trains[c]=b[c].split("~");a=this.Trains[c];if(c==0){this.Station_From=a[1];this.StationFromName=a[2];this.Station_To=a[3];this.StationToName=a[4];this.Error=a[5];if(a.length>=7){e=a[6].split("-");this.DataTime=new Date(e[0],parseInt(e[1])-
1,e[2],e[3],e[4],e[5])}}if(this.IsMainSearch==0&&c>0)a[T_After]=this.CalAfterHours(a)}this.Direction=0;this.IsMainSearch==1?this.ExtraSorts(T_Departure,4):this.ExtraSorts(T_After,25);this.IsMobile||Resized()}TrainList.prototype.UpdateRow=function(b){b--;var a=this.MakeTable(b);$("#divTrainsList"+this.ObjectName).find("tr:eq("+b+")").html(a);BindToolTip()};
TrainList.prototype.GetHightLight=function(b){return"<div style='padding: 0pt 0.7em; margin-top: 5px;' class='ui-state-highlight ui-corner-all'><p style='color:#363636;font-size:12px'><span style='float: left; margin-right: 0.3em;' class='ui-icon ui-icon-info'/>"+b+"</p></div>"};TrainList.prototype.GetStyle=function(b,a){if(a==undefined)a="";return"<td style='"+(this.CH[b][0]!=0&&this.IsMobile==0?"width:"+this.CH[b][0]+"px;":"")+(this.SortedCol==b?"background:#FFF4BF;":"")+a};
TrainList.prototype.ExtraSorts=function(b,a){if(this.SortedCol!=a)this.Direction=0;this.SortedCol=a;this.Direction=b>12&&b!=T_After&&b!=T_WaitTotal?0:!this.Direction;SortTableQ(b,a,this.Trains,this.Direction);this.MakeTable();return false};var NotFoundMessage="";
TrainList.prototype.MakeTable=function(b){if(this.Trains.length<2){var a=this.Trains[0][5];if("Train not found"==a){$(this.DataDiv).html("<br/><div style='width:100%;text-align:center;color:red'>"+T[122][L]+"</div>");return false}NotFoundMessage="<div style='text-align:center;color:red'>"+T[84][L]+" <br/>";if(a.indexOf("return parent.ShowURL")!=-1)try{urchinTracker("TrainsNotfound.aspx?From="+this.Trains[0][1]+"&To="+this.Trains[0][3])}catch(c){}Suggestion="";if(a.indexOf("SUGGESTION=")!=-1){Suggestion=
"<table boder='0' cellspacing='0' cellpadding='1' style='"+(this.IsMobile?"":"width:100%;")+"text-align:left;background-color:transparent'><tr> <td style='width:10px'><td>Suggestion - <a href='#' onclick='return ShowShortRoute()'>View On Map</a><td style='width:15px;'><a href='#' onclick='Suggestion=\"\";DisplayHistory()'>X</a>";var e=a.split("=");for(a=1;a<e.length;a++){b=e[a].split("-");for(d=1;d<b.length;d++){var g=b[d-1].split(":"),k=b[d].split(":");Suggestion+="<tr><td>";Suggestion+=d==1?a+"<td colspan='2' style='background-color:#FFF4BF;border-top:solid 1px #ADD1FF'>":
"<td colspan='2' style='background-color:#FFF4BF;'>";Suggestion+="<a href='#' onclick='ShowTrains(\""+g[0]+'","'+g[1]+'","'+k[0]+'","'+k[1]+"\")'>"+g[1]+Arrow+k[1]+"</a>"}}Suggestion+="</table>";NotFoundMessage+=T[86][L]}NotFoundMessage+="</div>";if(this.IsMobile)$(this.DataDiv).html(NotFoundMessage);else{ShowURL("rail/MapShortRoute.aspx?Stn1="+this.Trains[0][1]+"&Stn2="+this.Trains[0][3],1);DisplayHistory()}return false}g="<table class='DataTable DataTableHeader' border='0px' cellspacing='0px' cellpadding='0px'><tr style='height:15px;'>";
for(a=0;a<this.CH.length;a++)this.IsMainSearch&&(this.CH[a][3]==T_After||this.CH[a][3]==T_WaitTotal)||this.IsMobile&&(a>7||a==2)||(g+=this.GetStyle(a)+"'><a title3='"+this.CH[a][2]+"'href='#' onclick='return "+this.ObjectName+".ExtraSorts("+this.CH[a][3]+","+a+")'>"+(this.SortedCol==a?"<b>":"")+this.CH[a][1]+(this.SortedCol==a?"</b>":"")+"</a>");e=[""];if(this.IsMobile)e[e.length]=g;else{e[e.length]="<div id='divTrainsListHeader"+this.ObjectName+"'>"+g+"</table></div>";e[e.length]=["<div id='divTrainsList"+
this.ObjectName+"' style='overflow: auto;'>"];e[e.length]="<table class='DataTable' border='0px' cellspacing='0px' cellpadding='0px'>"}for(var l=k=g=0,d=0;d<7;d++){if($("#chkDepDay"+d).is(":checked"))g=1;if($("#chkArrDay"+d).is(":checked"))k=1;if($("#chkClass"+d).is(":checked"))l=1}var r="";FilterTrainType=FilterArrStn="";$("#divDepStns input").each(function(){if($(this).is(":checked"))r+=$(this).val()+","});$("#divArrStns input").each(function(){if($(this).is(":checked"))FilterArrStn+=$(this).val()+
","});$("#divTrainType input").each(function(){if($(this).is(":checked"))FilterTrainType+=$(this).val()+","});if(this.DataDiv!=""){for(a=1;a<this.Trains.length;a++){if(b!=undefined)if(b!=a-1)continue;var f=this.Trains[a];if(r!="")if(r.indexOf(f[T_StnFrom]+",")==-1)continue;if(FilterArrStn!="")if(FilterArrStn.indexOf(f[T_StnTo]+",")==-1)continue;if(FilterTrainType!="")if(FilterTrainType.indexOf(f[T_TrainType]+",")==-1)continue;if(g){var h=true;for(d=0;d<7;d++)if($("#chkDepDay"+d).is(":checked"))if(f[T_RunDays].charAt(d)==
1){h=false;break}if(h)continue}if(k){h=true;d=f[T_RunningDayToStn]-f[T_RunningDayFromStn];var q=f[T_RunDays].substring(0,7-d);q=f[T_RunDays].substring(7-d)+q;for(d=0;d<7;d++)if($("#chkArrDay"+d).is(":checked"))if(q.charAt(d)==1){h=false;break}if(h)continue}if(l){h=true;for(d=0;d<7;d++)if($("#chkClass"+d).is(":checked"))if(f[T_Classes].charAt(d)==1){h=false;break}if(h)continue}d=GetTrainNameColor(f[T_TrainType]);h=a%2?"#FFFFFF":"#fbf9ee";h=["<tr style='height:18px;background:"+h+"' IsSelected='0' OriginalClr='"+
h+"' onclick='return "+this.ObjectName+".TrainSelected("+this.ObjectName+".Trains["+a+"],this)'>"];if(b!=undefined)h=[""];h[h.length]=this.GetStyle(0)+"'><a href='#' title3='"+T[70][L]+"' style='color:#"+d+"'>"+f[T_No]+"</a>";q=this.IsMobile?"":GetRunMessage2(f[T_DateFrom],f[T_DateTo],f[T_RunDays]);h[h.length]=this.GetStyle(1)+"text-align: left;'>";h[h.length]="<a href='#' title2='"+GetTrainInfo(f)+"' style='color:#"+d+"'>"+(this.IsMobile?toTitleCase(f[T_Name]):f[T_Name])+"</a>";if(this.IsMobile==
0)h[h.length]=this.GetStyle(2)+"' "+(f[T_Pantry]=="1"?"title3='"+T[13][L]+"'>P":">");var o=f[T_StnFrom]==f[T_StnFirst];d=f[T_StnFromName]+(o?T[69][L]:"")+T[143][L];h[h.length]=this.GetStyle(3)+"' title3='"+d+"'><a href='#' onclick='mShowRoute=0;return GetRoute("+a+",0)'>"+(o?"<b title3='"+d+"'>"+f[T_StnFrom]+"</b>":f[T_StnFrom])+"</a>";h[h.length]=this.GetStyle(4,"'>")+f[T_Departure];o=f[T_StnTo]==f[T_StnLast];d=f[T_StnToName]+(o?T[68][L]:"")+T[143][L];h[h.length]=this.GetStyle(5)+"' title3='"+d+
"'><a href='#' onclick='mShowRoute=0;return GetRoute("+a+",1)'>"+(o?"<b title3='"+d+"'>"+f[T_StnTo]+"</b>":f[T_StnTo])+"</a>";h[h.length]=this.GetStyle(6,"'>")+f[T_Arrival];d=T[72][L]+f[T_Distance]+T[73][L]+f[T_AvSpeed]+T[74][L];h[h.length]=this.GetStyle(7,"'>")+(this.IsMobile?f[T_Travel]:"<a href='#' title3='"+d+"' onclick='mShowRoute=0;return cmdShowOnMap("+f[T_TrainID]+")'>"+f[T_Travel]+"</a>");if(this.IsMobile==0){h[h.length]=this.GetStyle(8)+"'>"+(f[T_RunDays]=="1111111"&&q==""?"&nbsp;":"<a href='#' onclick='mShowRoute=0' onmouseover=\"ShowCalendarFull('"+
f[T_RunDays]+"',0,0,'"+f[T_DateFrom]+"','"+f[T_DateTo]+"','"+f[T_ARP]+"')\" onmouseout=\"ShowCalendarFull('0')\" title3='"+(L==0?T[91][L]+" from "+f[T_StnFromName]:f[T_StnFromName]+T[76][L]+T[91][L])+"'>R</a>");for(d=9;d<=15;d++){h[h.length]=this.GetStyle(d)+"color:#"+(f[T_RunDays].charAt(d-9)==1?"009900'><b title3='"+T[75][L]+f[T_StnFromName]+T[76][L]+(L==0?d_names2[d-9]:d_names2L[d-9])+"'>Y</b>":"C0C0C0'><b>x</b>");f[T_Mon+(d-9)]=f[T_RunDays].charAt(d-9)}h[h.length]="<td width='5px'>&nbsp;";if(String(f[T_Classes]).indexOf("1")==
-1)h[h.length]="<td style='Color:#C0C0C0'>&nbsp;<td style='Color:#C0C0C0'><b>Un</b><td style='Color:#C0C0C0'><b>Re</b><td style='Color:#C0C0C0'><b>se</b><td style='Color:#C0C0C0'><b>rv</b><td style='Color:#C0C0C0'><b>ed</b><td>&nbsp;<td>&nbsp;";else{o=this.IsMobile?"":GetClassFareToolTip(f[T_Fare],0,f[T_TrainType]);var u=this.IsMobile?"":GetClassFareToolTip(f[T_Fare],1,f[T_TrainType]),n="";for(d=17;d<=24;d++){var m,s;if(o.length>=8){m=o[d-17];s=u[d-17];var p=d!=17;if(f[T_TrainType]=="SHATABDI")p=
true;n='<br/><table cellspacing=1 style="width:100%"><tr><th><th>'+T[90][L]+"<th>"+T[99][L];n+="<tr><td>"+T[80][L]+"<td>"+m[0]+"<td>"+(p?s[0]:"n/a");n+="<tr><td>"+T[81][L]+"<td>"+m[1]+"<td>"+(p?s[1]:"n/a");n+="<tr><td>"+T[82][L]+"<td>"+m[2]+"<td>"+(p?s[2]:"n/a");n+="<tr><td>"+T[83][L]+"<td>"+m[3]+"<td>"+(p?s[3]:"n/a");n+="<tr><td colspan=3>"+T[123][L]+"</table>"}m=new Date(IST_Time);if(q!=""){s=GetDate(f[T_DateFrom]);if(s>m)m=s}s=parseInt(f[T_Departure].split(".")[0]);p=parseInt(f[T_Departure].split(".")[1]);
m.setHours(s);m.setMinutes(p);n+="<br/>Booking Opening Dates at - "+f[T_StnFromName]+'<br/><table cellspacing=1 style="width:100%"><tr><th>Travel Date<th>Tatkal Opens At';var t=parseInt(f[T_RunningDayFromStn]);for(s=0;s<10;s++){m=GetNextRunDate2(m,f[T_RunDays]);p=new Date(m.getTime()-OneDay*t);p.setHours(10);p.setMinutes(0);n+="<tr><td>"+FormatDate(m,"dd-M");if(m<IST_Time)n+='<td style="color:red">Closed';else if(p<IST_Time)n+='<td style="color:green">Open *';else{n+="<td>";n+=FormatDate(p,"dd-M")+
", 10am"}m.setTime(m.getTime()+OneDay);if(p>IST_Time)break}n+="</table>* Open till chart is prepared";p=parseInt(f[T_ARP]);if(p==90)p=120;p+=t;m=new Date(IST_Time);m.setHours(23);m.setMinutes(59);var v=new Date(m.getTime());t=null;var w=new Date(IST_Time.getTime()+(p-1)*OneDay);for(s=0;s<122;s++){v=GetNextRunDate2(v,f[T_RunDays]);m.setTime(v.getTime()+OneDay);m=GetNextRunDate2(m,f[T_RunDays]);if(m>=w)break;t=new Date(m);v.setTime(v.getTime()+OneDay)}n+='<br/><br/><table cellspacing=1 style="width:100%"><tr><th>Travel Date<th>General Opens At';
n+="<tr><td>Till "+FormatDate(v,"dd-M")+"<td>Open";t.setTime(v.getTime()+OneDay);t=GetNextRunDate2(t,f[T_RunDays]);m=new Date(t.getTime()-(p-1)*OneDay);n+="<tr><td>"+FormatDate(t,"dd-M")+"<td>"+(IST_Time.getHours()<8?FormatDate(m,"dd-M")+", 8am":"Open");t.setTime(t.getTime()+OneDay);t=GetNextRunDate2(t,f[T_RunDays]);m=new Date(t.getTime()-(p-1)*OneDay);n+="<tr><td>"+FormatDate(t,"dd-M")+"<td>"+FormatDate(m,"dd-M")+", 8am";n+="</table>";h[h.length]=this.GetStyle(d)+"color:#"+(f[T_Classes].charAt(d-
17)==1?"cd853f'><b><A href='#' title2='"+T[54][L]+"<b>"+n_Classes[d-16]+"</b>"+n+"' onclick='mShowRoute=0;mClass=\""+n_Classes[d-16]+"\"'>Av</A></b>":"C0C0C0'><b>x</b>");f[T_1A+(d-17)]=f[T_Classes].charAt(d-17)}}if(this.IsMainSearch==0){o=parseInt(f[T_After].split(".")[0],10);u=parseInt(f[T_After].split(".")[1],10);d="";if(TrainsObj!=null&&TrainsObj.SelectedTrain!=null){n=TrainsObj.SelectedTrain;q=this.GetMinutes(n[T_Travel]);d="<table class='Transparent' cellspacing='0px' cellpadding='0px'>";d+=
"<tr><td>"+$.datepicker.formatDate("dd-M",this.FirstTrainDepTime)+"<td>"+n[T_Departure]+"<td>Depart";d+="<tr><td><td>"+Math.floor(q/60)+" hr "+q%60+" min<td>Travel";d+="<tr><td>"+$.datepicker.formatDate("dd-M",this.FirstTrainArrTime)+"<td>"+n[T_Arrival]+"<td>Arrive";d+="<tr><td colspan='3'><hr/>";d+="<tr><td><td>"+o+" hr , "+u+" min<td>Wait";d+="<tr><td colspan='3'><hr/>";n=new Date(this.FirstTrainArrTime.getTime()+o*36E5+u*6E4);d+="<tr><td>"+$.datepicker.formatDate("dd-M",n)+"<td>"+f[T_Departure]+
"<td>Depart";q+=o*60+u;o=this.GetMinutes(f[T_Travel]);q+=o;u=new Date(n.getTime()+o*60*1E3);d+="<tr><td><td>"+Math.floor(o/60)+" hr "+o%60+" min<td>Travel";d+="<tr><td>"+$.datepicker.formatDate("dd-M",u)+"<td>"+f[T_Arrival]+"<td>Arrive";d+="</table>";o=Math.floor(q/60);u=q%60;f[T_WaitTotal]=(o<10?"00"+o:o<100?"0"+o:o)+"."+(u<10?"0"+u:u)}h[h.length]=this.GetStyle(25)+"text-align:right;' title2=\""+d+'">'+f[T_After];h[h.length]=this.GetStyle(26)+"text-align:right;'>"+f[T_WaitTotal]}}if(b!=undefined)return h.join("");
h[h.length]="</tr>";e[e.length]=h.join("")}e[e.length]="</table>";a=this.Trains[0];e[e.length]="<br/><div id='divExtraInfo'><table cellspacing='0px' cellpadding='0px' style='width:100%'><tr><td valign='top'>";if(this.IsMobile==0)if(this.IsMainSearch){e[e.length]=this.Tools(a);e[e.length]="<tr><td>"+(SearchType==2?"<div style='margin:auto;width:70%;text-align:center;' class='ui-state-highlight'>"+T[130][L]+"</div>":HelpInfo())}else e[e.length]="<tr><td><div style='margin:auto;width:70%;text-align:center;' class='ui-state-highlight'>"+
T[136][L]+"</div>";e[e.length]="</table></div><br/></div>";a="#divTrainsList"+this.ObjectName;$(this.DataDiv).html(e.join(""));$(a+" tr").mouseover(function(){$(this).css("background","#dfcef2")});$(a+" tr").mouseout(function(){$(this).attr("IsSelected")=="0"&&$(this).css("background",$(this).attr("OriginalClr"))});if(this.IsMobile){$(this.DataDiv).css({overflow:"none",height:"auto"});$(a).css({overflow:"none",height:"auto",width:"auto"})}else{Resized();BindToolTip()}}};
function GerClassNames(b){var a="";$(n_Classes).each(function(c){if(b[c-1]=="1")a+=this+" "});return a}function GerRundaysNames(b){var a="";$(d_names2S).each(function(c){if(b[c]=="1")a+=this+" "});return a}
function GetTrainInfo(b){GetRunMessage2(b[T_DateFrom],b[T_DateTo],b[T_RunDays]);var a='<table cellpadding=0 cellspacing=1 style="width:280px"><tr><td style="width:80px;">No.<td>'+b[T_No]+"<tr><td>Name<td>"+b[T_Name]+"<tr><td>From/To<td>"+b[T_StnFirstName]+T[93][L]+b[T_StnLastName]+"<tr><td>ARP<td>"+b[T_ARP]+"<tr><td>Run Days<td>"+GerRundaysNames(b[T_RunDays]);a+="<tr><td>Classes<td>"+GerClassNames(b[T_Classes])+"<tr><td>General Class<td>"+(b[T_Flags][F_Show_General_Fare]=="1"?"Yes":"No")+"<tr><td>Fare Type<td>"+
b[T_TrainType]+"<tr><td>Train Type<td>"+b[T_TrainType2]+"<tr><td>Owned By<td>"+b[T_OwningRailway]+"<tr><td>Gauge<td>"+b[T_Guage]+"<tr><td>Pantry<td>"+(b[T_Pantry]=="1"?"Yes":"No")+"<tr><td>Food Cost<td>"+(b[T_Flags][F_Food_Cost_Included]=="1"?"Included in fare":"");if(b[T_AdminNote]!="")a+="<tr><td>Note<td>"+b[T_AdminNote];if(b[T_Note]!="")a+='<tr><td title="Additional Information">Add. Info<td>'+b[T_Note];return a}
function GetTrainNameColor(b){var a="000000";switch(b){case "SHATABDI":a="006AD5";break;case "RAJDHANI":a="FF480B";break;case "RAIL_MOTOR":a="008000";break;case "SUPERFAST":a="D56A00";break;case "MAIL_EXPRESS":a="8B4513";break;case "COMPOSITE":a="556B2F"}return a}
TrainList.prototype.Tools=function(b){var a="<table cellspacing='0px' cellpadding='5px' style='width:100%'><tr>";if(DataSource<10){a+="<td>"+T[57][L]+" <input onfocus='this.select()' style='width: 200px' type='text' title3='"+T[110][L]+"' value='http://erail.in?";a+=SearchType==0?"T="+b[1]+"::"+b[3]+":' />":SearchType==1?"R="+$("#txtTrain_no").val()+"' />":"V="+(Direction==1?mStation_From+":"+mStation_Via+":"+mStation_To:mStation_To+":"+mStation_Via+":"+mStation_From)+"' />"}a+="<td><input type='button' style='cursor:pointer;' title3='"+
T[58][L]+"' onclick='PrintTrains();' value='"+T[56][L]+"' />";a+="<td><input type='button' style='cursor:pointer;' title3='"+T[131][L]+"' onclick='return "+this.ObjectName+".ShowAdvanceFilter()' value='"+T[55][L]+"' />";a+="</table>";return a};TrainList.prototype.GetMinutes=function(b){return b.indexOf(".")!=-1?parseInt(b.split(".")[0],10)*60+parseInt(b.split(".")[1],10):0};
TrainList.prototype.ShowAdvanceFilter=function(){var b="<br/><table id='tableFilter' style='margin: auto;width: 770px' cellpadding='2' cellspacing='1'>";b+="<tr><th>"+T[100][L];b+="<th>"+T[105][L];b+="<th>"+T[101][L];b+="<th>"+T[106][L];b+="<th>"+T[102][L];b+="<th>"+T[107][L];b+="<tr><td><table cellpadding='0' cellspacing='0'>";b+="<tr><td><input id='txtDepartDateFilter' style='width:80px' /><input  type='button' style='cursor:pointer' value='Show' onclick='"+this.ObjectName+'.RunDateFilter("#txtDepartDateFilter")\' />';
for(var a=0;a<7;a++)b+="<tr><td><input id='chkDepDay"+a+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' />"+(L==0?d_names2S[a]:d_names2SL[a]);b+="</table><td valign='top'><table id='divDepStns' cellpadding='0' cellspacing='0'>";var c="";for(a=1;a<this.Trains.length;a++){var e=this.Trains[a][T_StnFrom]+",";if(c.indexOf(e)==-1){c+=e;b+="<tr><td><input id='chkDepStn"+a+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' value='"+this.Trains[a][T_StnFrom]+"' />"+this.Trains[a][T_StnFromName]}}b+=
"</table><td valign='top'><table cellpadding='0' cellspacing='0'>";b+="<tr><td><input id='txtArrDateFilter' style='width:80px' /><input  type='button' style='cursor:pointer' value='Show' onclick='"+this.ObjectName+'.RunDateFilter("#txtArrDateFilter")\' />';for(a=0;a<7;a++)b+="<tr><td><input id='chkArrDay"+a+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' />"+(L==0?d_names2S[a]:d_names2SL[a]);b+="</table><td valign='top'><table id='divArrStns' cellpadding='0' cellspacing='0'>";c="";for(a=
1;a<this.Trains.length;a++){e=this.Trains[a][T_StnTo]+",";if(c.indexOf(e)==-1){c+=e;b+="<tr><td><input id='chkArrStn"+a+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' value='"+this.Trains[a][T_StnTo]+"'/>"+this.Trains[a][T_StnToName]}}b+="</table><td valign='top'><table cellpadding='0' cellspacing='0'>";for(a=1;a<=7;a++)b+="<tr><td><input id='chkClass"+(a-1)+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' />"+n_Classes[a];b+="</table><td valign='top'><table id='divTrainType' cellpadding='0' cellspacing='0'>";
c="";for(a=1;a<this.Trains.length;a++){e=this.Trains[a][T_TrainType]+",";if(c.indexOf(e)==-1){c+=e;b+="<tr><td><input id='chkTrainType"+a+"' type='checkbox' onclick='"+this.ObjectName+".MakeTable()' value='"+this.Trains[a][T_TrainType]+"'/>"+this.Trains[a][T_TrainType]}}b+="</table></table><input type='button' style='cursor:pointer' onclick='"+this.ObjectName+".ClearFilter()' value='"+T[111][L]+"'/>";$("#divDetail").html(b);$("#txtDepartDateFilter").datepicker({dateFormat:"dd-M-yy"});$("#txtArrDateFilter").datepicker({dateFormat:"dd-M-yy"});
$("#txtDepartDateFilter").datepicker("setDate",IST_Time);$("#txtArrDateFilter").datepicker("setDate",IST_Time);return false};
TrainList.prototype.CalcFirstTrainTime=function(){this.FirstTrainArrTime=null;if(!(TrainsObj==null||TrainsObj.SelectedTrain==null)){var b=new Date(Direction==1?DateFromTo:DateToFrom),a=TrainsObj.SelectedTrain;b=GetNextRunDate2(b,a[T_RunDays]);b.setHours(0,0,0,0);this.FirstTrainDepTime=new Date(b.getTime()+this.GetMinutes(a[T_Departure])*6E4);this.FirstTrainArrTime=new Date(this.FirstTrainDepTime.getTime()+this.GetMinutes(a[T_Travel])*6E4)}};
TrainList.prototype.CalAfterHours=function(b){if(this.FirstTrainArrTime==null)return"";var a=new Date(this.FirstTrainArrTime.getTime());a.setHours(0,0,0,0);a=GetNextRunDate2(a,b[T_RunDays]);a=new Date(a.getTime()+this.GetMinutes(b[T_Departure])*6E4);a.getTime()<this.FirstTrainArrTime.getTime()&&a.setTime(a.getTime()+OneDay);a=GetNextRunDate2(a,b[T_RunDays]);a=Math.floor((a.getTime()-this.FirstTrainArrTime.getTime())/6E4);b=Math.floor(a/60);a=a%60;return(b<10?"00"+b:b<100?"0"+b:b)+"."+(a<10?"0"+a:
a)};TrainList.prototype.RunDateFilter=function(b){var a=$(b).datepicker("getDate").getDay();if(a==0)a=7;a-=1;for(var c=0;c<7;c++){$("#chkDepDay"+c).attr("checked",false);$("#chkArrDay"+c).attr("checked",false)}$((b=="#txtDepartDateFilter"?"#chkDepDay":"#chkArrDay")+a).attr("checked",true);this.MakeTable()};TrainList.prototype.ClearFilter=function(){$("#tableFilter input:checkbox").each(function(){$(this).attr("checked",false)});this.MakeTable()};
TrainList.prototype.GetFare=function(b,a,c,e,g,k){var l=0,d=0,r="";switch(a){case "1A":d=0;break;case "2A":d=1;break;case "3A":d=2;break;case "CC":d=3;break;case "FC":d=4;break;case "SL":d=5;break;case "2S":d=6;break;case "3E":d=7}for(var f=1;f<this.Trains.length;f++){var h=this.Trains[f],q=0;if(h[T_No]==b){if(h[T_Classes][d]=="0")r=a+" is not available in "+b;l=GetClassFareToolTip(h[T_Fare],g=="CK"?1:0,h[T_TrainType]);q=0;if(k)q=e=="M"?2:3;if(c<=12)q=1;l=l[d][q]}}return{Fare:l,Message:r}};
TrainList.prototype.TrainSelected=function(b,a){if(this.lastSelectedRow){$(this.lastSelectedRow).attr("IsSelected","0");$(this.lastSelectedRow).css("background",$(this.lastSelectedRow).attr("OriginalClr"))}if(a){$(a).attr("IsSelected","1");$(a).css("background","#dfcef2");this.lastSelectedRow=a}this.SelectedTrain=b;ShowRoute(b,this.IsMainSearch)};
function SortTableQ(b,a,c,e){a=0;for(var g=1;g<c.length;g++){for(var k=a=g;k<c.length;k++)if(c[a][b]>c[k][b]&&e||c[a][b]<c[k][b]&&!e)a=k;if(a!=g){k=c[g];c[g]=c[a];c[a]=k}}return false}
function GetClassFareToolTip(b,a,c){for(var e=[],g=1;g<=8;g++)e.push("");try{var k=b.split(":");for(g=1;g<=8;g++){var l=b=0,d=0,r=0,f=k[g+1].split(",");b=l=d=r=f[0];l=f[1];if(c!="RAIL_MOTOR"){d=f[2];r=l;if(f.length>=4)r=f[4]}if(a==1){b=d=r=parseInt(f[0])+parseInt(f[3]);l=parseInt(f[1])+parseInt(f[3])}e[g-1]=[];e[g-1][0]=b;e[g-1][1]=l;e[g-1][2]=d;e[g-1][3]=r}}catch(h){}return e}
function GetRunMessage2(b,a,c){var e=new Date(IST_Time.getTime()+OneDay*90);b=GetDate(b);a=new Date(GetDate(a).getTime()-OneDay);return GetRunMessage3(e,b,a,c)}function GetRunMessage3(b,a,c,e){if(b<a||b>c){a=GetNextRunDate2(a,e);return"Train runs between "+a.toDateString()+" and "+c.toDateString()}return""}function GetRunMessage(b,a,c,e){a=GetDate(a);c=GetDate(c);return GetRunMessage3(b,a,c,e)}function GetDate(b){b=b.split("-");var a=0;a=b[1];a--;return new Date(b[0],a,b[2])}
function GetNextRunDate2(b,a){for(var c=new Date(b),e=0;;){e=c.getDay()==0?6:c.getDay()-1;if(a.charAt(e)=="1")break;c.setTime(c.getTime()+OneDay)}return c}function GetNextRunDate(b){b=new Date(b);for(var a=0;;){a=b.getDay()==0?T_Sun:T_Mon+b.getDay()-1;if(STrain[a]=="1")break;b.setTime(b.getTime()+OneDay)}return b}function toTitleCase(b){return b.replace(/\w\S*/g,function(a){return a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()})}
function GetFormattedDate(b,a){var c=new Date(IST_Time.getTime()+b*OneDay),e=c.getDate()<10?"0"+c.getDate():c.getDate(),g=c.getMonth()+1;g=g<10?"0"+g:g;return a?e+" "+m_names[c.getMonth()]:e+" "+g+" "+c.getFullYear()}
var TR_No=0,TR_StnCode=1,TR_StnName=2,TR_Arrival=3,TR_Departure=4,TR_Halt=5,TR_Distance=6,TR_Day=7,TR_Platform=8,TR_Remark=9,TR_Zone=10,TR_Division=11,CHR=[[35,T[35][L],T[36][L],TR_No],[45,T[37][L],T[46][L],TR_StnCode],[130,T[38][L],T[47][L],TR_StnName],[45,T[103][L],T[103][L],TR_Zone],[45,T[104][L],T[104][L],TR_Division],[60,T[39][L],T[48][L],TR_Arrival],[60,T[40][L],T[49][L],TR_Departure],[35,T[41][L],T[50][L],TR_Halt],[35,T[42][L],T[142][L],TR_Platform],[45,T[43][L],"",TR_Distance],[35,T[44][L],
"",TR_Day],[186,T[45][L],"",TR_Remark]];function RouteList(b,a,c){this.IsMobile=c==undefined?0:c;b=b.split("^");this.Route=[];this.DataDiv="#"+a;for(i=0;i<b.length;i++){b[i]+="~~~";this.Route[i]=b[i].split("~")}if(a!=undefined){this.MakeTable();this.IsMobile||Resized()}}RouteList.prototype.GetStyle=function(b){return this.IsMobile?"<td style='":"<td style='width:"+CHR[b][0]+"px;"};var RouteDistance=0;
RouteList.prototype.MakeTableFare=function(){if(STrain!=null){var b="<table id='tablefaredetail' class='DataTable' border='0px' cellspacing='0px' cellpadding='0px' bgcolor='#C5EAFE' width='750px'>";b+="<tr style='background: #f2e6ce'><td style='background: #FFFFFF; color: #AC59FF' colspan='2'>"+STrain[T_No]+" "+STrain[T_Name]+"<td rowspan='3'>";b+="<table border='0px' cellspacing='0px' cellpadding='0px' style='width:100%' >";b+="<tr><td rowspan='2' width='50px' style='background: #f2e6ce'>";b+="Fare&nbsp;<span style='color: #ff0000'>*</span><td>1A<td>2A<td>3A<td>CC<td>FC<td>SL<td>2S<td>GN<td style='background: #FFFFFF; width: 20px'>";
b+="<select id='selectAdult' title='12 years to 59 years' size='1' style='background-color: #ffffff; font-size: 10px;width:60px;' onchange=\"CalcFare()\">";for(var a=0;a<7;a++)b+="<option value='"+a+"' "+(a==1?"selected='true'":"")+">"+a+T[80][L];b+="</select><td style='background: #FFFFFF; width: 20px'><select id='selectChild' title='"+T[87][L]+"' size='1' style='width:60px;background-color: #ffffff;font-size: 10px;' onchange=\"CalcFare()\">";for(a=0;a<7;a++)b+="<option value='"+a+"'>"+a+T[81][L];
b+="</select><tr style='height:18px'><td id='tdFareRs1' width='46px'>";b+="<td id='tdFareRs2' width='46px'><td id='tdFareRs3' width='46px'>";b+="<b><td id='tdFareRs4' width='44px'><td id='tdFareRs5' width='44px'>";b+="<td id='tdFareRs6' width='44px'><td id='tdFareRs7' width='40px'>";b+="<td id='tdFareRs9' width='40px'>";b+="<td style='background: #FFFFFF;' colspan='2'><select id='selectSenior' title='"+T[88][L]+"' size='1' style='background-color: #ffffff;width:125px;font-size: 10px;' onchange=\"CalcFare()\">";
for(a=0;a<7;a++)b+="<option value='"+a+"'>"+a+T[82][L];b+="</select><tr style='background: #FFFFFF'><td style='background: #f2e6ce'>";b+="<select id='selectCurrency' size='1' style='background-color: #ffffff; font-size: 10px;' onchange=\"CalcFare()\">";b+="<option value='USD'>USD<option value='AUD'>AUD<option value='CAD'>CAD<option value='CHF'>CHF<option value='EUR'>EUR<option value='GBP'>GBP<option value='HKD'>HKD<option value='JPY'>JPY<option value='KWD'>KWD<option value='NZD'>NZD<option value='RUB'>RUB<option value='SGD'>SGD<option value='THB'>THB</select>";
b+="<td id='tdFareEx1'><td id='tdFareEx2'><td id='tdFareEx3'><td id='tdFareEx4'><td id='tdFareEx5'><td id='tdFareEx6'><td id='tdFareEx7'><td id='tdFareEx9'><td style='background: #FFFFFF;' colspan='2'>";b+="<select id='selectSeniorF' title='"+T[89][L]+"' size='1' style='background-color: #ffffff;font-size: 10px;width:125px;' onchange=\"CalcFare()\">";for(a=0;a<7;a++)b+="<option value='"+a+"'>"+a+T[83][L];b+="</select></table>";b+="<tr style='background: #fcf8f0'><td style='background: #FFFFFF; color: #AC59FF' colspan='2'>"+
STrain[T_StnFromName]+T[93][L]+STrain[T_StnToName];b+="<tr><td style='border-right: #cccccc 0px solid;'><a id='aPrint' href='#' onclick='PrintRoute()'>"+T[113][L]+"</a><td>"+T[72][L]+RouteDistance+" kms</table>";$("#divFare").html(b);CalcFare();return b}};
RouteList.prototype.MakeTable=function(){if(this.Route.length<2)$(this.DataDiv).html("<div style='text-align:center;'><br/>Route Not Found or Train is cancelled</div>");else{var b=this.Route[0],a="<div id='divFare'></div>";a+="<table class='DataTable DataTableHeader' "+(this.IsMobile?"":"width='750px'")+" border='0px' cellspacing='0px' cellpadding='0px'>";a+="<tr height='15px'>";for(i=0;i<CHR.length;i++){if(this.IsMobile)if(i==3||i==4||i==8||i==11)continue;a+="<td "+(this.IsMobile?"":"style='width:"+
CHR[i][0]+"px'")+" title3='"+CHR[i][2]+"'>"+CHR[i][1]}if(this.IsMobile==0){a+="</table><div id='divRouteList' style='overflow: auto; position: relative;'>";a+="<table class='DataTable' width='750px' border='0px' cellspacing='0px' cellpadding='0px'>"}var c=0,e=0,g=0,k=true;for(i=1;i<this.Route.length;i++){b=this.Route[i];var l=i%2?"#FFFFFF":"#FBF8EB";if(STrain!=null){if(b[TR_StnCode]==STrain[T_StnFrom]){c=b[TR_Distance];l="#FFF4BF;";k=false}if(b[TR_StnCode]==STrain[T_StnTo]){e=b[TR_Distance];l="#FFF4BF;"}}if(k)g+=
18;a+="<tr height='18px' style='background:"+l+(l=="#FFF4BF;"?"font-weight:bold;":"")+"'>";a+=this.GetStyle(0)+"'>"+b[TR_No];a+=this.GetStyle(1)+"'>"+b[TR_StnCode];a+=this.GetStyle(2)+";text-align:left'><a href='#' title3='"+b[TR_StnName]+"-"+b[TR_Zone]+"-"+b[TR_Division]+"'>"+b[TR_StnName]+"</a>";if(this.IsMobile==0){a+=this.GetStyle(3)+"'>"+b[TR_Zone];a+=this.GetStyle(4)+"'>"+b[TR_Division]}a+=this.GetStyle(5)+"'>"+b[TR_Arrival];a+=this.GetStyle(6)+"'>"+b[TR_Departure];a+=this.GetStyle(7)+"'>"+
b[TR_Halt];if(this.IsMobile==0)a+=this.GetStyle(8)+"'>"+b[TR_Platform];a+=this.GetStyle(9)+"'>"+b[TR_Distance];a+=this.GetStyle(10)+"'>"+b[TR_Day];if(this.IsMobile==0)a+=this.GetStyle(11)+"'>&nbsp;"+b[TR_Remark]}RouteDistance=e-c;a+="</table>";if(this.IsMobile==0)a+="<br/><div id='divRake'></div><br/><div id='divExtraInfo'><span style='color: #ff0000'><i>* "+T[63][L]+"</i></span></div></div>";$(this.DataDiv).html(a);if(this.IsMobile==0){BindToolTip();$("#divRouteList").animate({scrollTop:g},"slow");
try{this.MakeTableFare()}catch(d){}Resized();GetRake()}}};
function UpdateTrainData(b,a,c,e,g,k){var l=TrainsObj.Trains[b],d=a!=""?T_StnTo:T_StnFrom;l[d]=a!=""?a:c;d=a!=""?T_StnToName:T_StnFromName;l[d]=e;d=a!=""?T_Arrival:T_Departure;l[d]=k.replace(":",".");if(c!=""){RunDayDiff=g-l[T_RunningDayFromStn];a=l[T_RunDays];c=a.length;if(RunDayDiff>0)for(e=0;e<RunDayDiff;e++)a=a[c-1]+a.substring(0,c-1);else if(RunDayDiff<0)for(e=0;e<Math.abs(RunDayDiff);e++)a=a.substring(1)+a[0];l[T_RunningDayFromStn]=g;l[T_RunDays]=a}ShowStationSelection();TrainsObj.UpdateRow(b);
return false}
function ShowStationSelection(b,a,c){if(b==undefined)$("#divStnSelection").css("visibility","hidden");else if(TrainsObj!=null){var e=TrainsObj.Trains[a];StnSelection=new RouteList(b);var g="<table cellpadding='0' cellspacing='1' style='width:100%'><tr><td colspan='4' style='text-align:right'><a href='#' onclick='ShowStationSelection()'><b>Close</b></a>";g+="<tr><td colspan='4' style='color:red'>Click Station Name to change "+(c?"arrival":"departure")+" station";var k=0;$(StnSelection.Route).each(function(d){if(d>0&&
(c==0&&this[TR_StnCode]==e[T_StnFrom]||c==1&&this[TR_StnCode]==e[T_StnTo]))k=parseInt(this[TR_Distance])});var l=c?false:true;$(StnSelection.Route).each(function(d){if(d>0){var r="style='white-space:nowrap;";if(this[TR_StnCode]==e[T_StnFrom]){if(c)l=true;r+="background-color:#d4ffaa"}else if(this[TR_StnCode]==e[T_StnTo]){if(c==0)l=false;r+="background-color:#ffddcb"}r+="'";var f="href='#' onclick ='return UpdateTrainData("+a+',"'+(c?this[TR_StnCode]:"")+'","'+(c?"":this[TR_StnCode])+'","'+this[TR_StnName]+
'",'+this[TR_Day]+',"'+(c?this[TR_Arrival]:this[TR_Departure])+"\")'";l||(f="style='color:#c0c0c0'");g+="<tr><td>"+d+"<td "+r+"><a "+f+">"+this[TR_StnName]+"</a><td>"+this[TR_StnCode]+"<td>"+(parseInt(this[TR_Distance])-k)}});g+="</table>";$("#divStnSelection").html(g);$("#divStnSelection").css({height:$("#divMain").height(),width:285,visibility:"visible",left:$("#accordion").offset().left,top:$("#divMain").offset().top})}}var StnSelection=null;
function GetRoute(b,a){$.ajax({cache:CacheFlag,url:"Rail/GetTrainRoute.aspx?TrainID="+TrainsObj.Trains[b][T_TrainID]+"&Language="+L,success:function(c){ShowStationSelection(c,b,a)}});return false}
var CoachTip=["A","2AC","AB","2AC+3AC","B","3AC","C","AC Chair Car","D","Second Sitting (Reserved)","DR","Second Class","EC","Executive AC chair car","F","First Class","FC","First Class","FS","First Class Cum Sitting","G","3AC","GC","Generator","H","First AC","HA","First AC+2AC","HB","First AC+3AC","J","AC Chair Car","PC","Pantry","GLR","Luggage","GLRD","Disabled + Luggage","GS","General","GSD","General + Disabled ","GSL","General + Ladies","GSLR","General + Luggage","GSLRD","General + Luggage + Disabled",
"GSR","Second Class","GSRD","General + Disabled","RMS","Rail Mail Service","S","Sleeper","SLR","Sitting + Luggage","VP","Parcel Van","VPH","High Capacity Parcel Van","VPU","Motor Cum Parcel Vans","VVN","Milk Van"];
function GetRake(){if(STrain!=null){$.ajax({cache:CacheFlag,url:"Data.aspx?Action=RAKE&Data1="+STrain[T_TrainID]+"&Language="+L,success:function(b){b=b.split("~");if(b.length!=0){var a="Standard Coach Compostion and NOT actual train postioning from engine: (<i>Temporary coaches are not shown</i>) <table cellspacing='1' cellpadding='0' style='width:100%;text-align:center'><tr>",c=100/b.length;$(b).each(function(k){a+="<td style='width:"+c+"%'>"+(k>0?k:"")});a+="<tr>";var e="<br/><div>",g=[];$(b).each(function(){var k=
this.split(" ");a+="<td class='"+k[0]+"'>"+this.replace(" ","").replace("-","");var l=false;$(g).each(function(){if(this==k[0])l=true});if(!l){g.push(k[0]);for(var d=0;d<CoachTip.length;d+=2)if(CoachTip[d]==k[0]){e+="<span style='margin:3px;border:1px solid #c0c0c0;' class='"+k[0]+"'>"+k[0]+" - <i>"+CoachTip[d+1]+"</i></span>";break}}});a+="</table>"+e+"</div>";$("#divRake").html(a)}}});return false}}var ADStation="";
function TrainListAD(b,a,c,e,g){this.IsMobile=c==undefined?0:c;this.Trains=[];this.SortedCol=0;this.DataDiv="#"+a;this.SortedCol=0;this.Display=e==undefined?0:e;this.DisplayType=g;this.CAD=[[70,"Train","Train Number",T_No],[250,"Train Name","Train Name",T_Name],[55,"Orig.","First Station",T_StnFirst],[55,"Des.","Last Station",T_StnLast],[55,"Arr.","Arrival Time at the To Station",T_Arrival],[55,"Dep.","Departure Time at the selected station",T_Departure],[55,"Halt.","Halt",T_Travel],[15,"&nbsp;",
"",0],[20,"M","Monday",T_Mon],[20,"T","Tuesday",T_Tues],[20,"W","Wednesday",T_Wed],[20,"T","Thursday",T_Thur],[20,"F","Friday",T_Fri],[20,"S","Saturday",T_Sat],[20,"<span style='color: red'>S</span>","Sunday",T_Sun]];b=b.split("^");for(i=0;i<b.length;i++){a=b[i].split("~");if(this.IsMobile)this.DisplayType=="A"&&a[T_Arrival]=="First"||this.DisplayType=="D"&&a[T_Departure]=="Last"||this.Trains.push(a)}Dir=1;this.MakeTable();this.IsMobile==0&&Resized()}
TrainListAD.prototype.ExtraSorts=function(b,a){if(this.SortedCol!=a)this.Direction=0;this.SortedCol=a;this.Direction=b>12?0:!this.Direction;SortTableQ(b,a,this.Trains,this.Direction);this.MakeTable();return false};TrainListAD.prototype.GetStyle=function(b,a){if(a==undefined)a="";return(this.IsMobile?"<td style='":"<td style='width:"+this.CAD[b][0]+"px;"+(this.SortedCol==b?"background:#FFF4BF;":""))+a};
TrainListAD.prototype.MakeTable=function(){if(this.Trains.length<2)$(this.DataDiv).html("<div style='text-align:center;'><br/>No trains found for the selections</div>");else{var b="<table class='tableBorder' "+(this.IsMobile?"":"width='750px'")+" border='0px' cellspacing='0px' cellpadding='0px' style='text-align: center; font-size: 12px; font-family: Arial;'><thead>",a="<tr style='height:15px;background: #C5EAFE;'>";for(i=0;i<this.CAD.length;i++){a+=(this.IsMobile?"<td>":"<td style='width:"+this.CAD[i][0]+
"px'>")+"<a title3='"+this.CAD[i][2]+"' href='#' onclick='TrainsObjAD.ExtraSorts("+this.CAD[i][3]+","+i+");return TrainsObjAD.MakeTable();'>"+(this.SortedCol==i?"<b>":"")+this.CAD[i][1]+(this.SortedCol==i?"</b>":"")+"</a>";if(i==6&&this.IsMobile)break}if(this.IsMobile==0){b+=a+"</tr></thead></table>";b+="<div id='divTrainsList' style='overflow: auto; height: 85px; position: relative;'>";b+="<table class='tableBorder' width='750px' border='0px' cellspacing='0px' cellpadding='0px'style='text-align: center; font-size: 12px; font-family: Arial;'>"}else b+=
a+"</tr></thead>";b+="<tbody id='tblTrainsList'>";for(i=1;i<this.Trains.length;i++)try{var c=this.Trains[i],e=GetTrainNameColor(c[T_TrainType]);b+="<tr style='height:18px;background:"+(i%2?"#FFFFFF":"#FBF8EB")+"' onclick='return ShowRoute(TrainsObjAD.Trains["+i+"],this)'>";b+=this.GetStyle(0)+"text-align: Left;' title=''>"+c[T_No];b+=this.GetStyle(1)+"color:#"+e+"; text-align: left;' title3='"+c[T_Name]+" - "+c[T_TrainType]+"'>"+(this.IsMobile?toTitleCase(c[T_Name]):c[T_Name]);b+=this.GetStyle(2)+
"' title3='"+c[T_StnFirstName]+"'>"+c[T_StnFirst];b+=this.GetStyle(3)+"' title3='"+c[T_StnLastName]+"'>"+c[T_StnLast];b+=this.GetStyle(4)+"'>"+c[T_Arrival];b+=this.GetStyle(5)+"'>"+c[T_Departure];b+=this.GetStyle(6)+"'>"+c[T_Travel];if(this.IsMobile==0){b+=this.GetStyle(7)+"'>&nbsp;";for(j=8;j<=14;j++)b+=this.GetStyle(j)+"color:#"+(c[T_RunDays].charAt(j-8)==1?"009900'><b>Y</b>":"C0C0C0'><b>x</b>")}b+="</tr>"}catch(g){}b+="</tbody></table>";if(this.IsMobile==0){b+="<br/><a href='#' onclick='PrintTrains();'>Click here to print trains list</a><br/>";
b+=T[57][L]+"&nbsp;<input onfocus='this.select()' style='width: 400px' type='text' value='http://erail.in?AD="+ADStation+"'/></div>"}$(this.DataDiv).html(b);this.IsMobile==0&&Resized();return false}};
